# 8.1.3 Math Functions with Numpy/SciPy: Matrix Operations

######

## I. Create two ndarrays

In [1]:
# Create ndarrays containing 10 random number
import numpy as np

ndarray1 = np.array([[1,-24,2],[78,5,9],[12,8,49]])
ndarray2 = np.array([[0,1,100],[1,25,61],[-2,8,1]])

## II. Calculate inner product

In [2]:
np.inner(ndarray1, ndarray2)

array([[ 176, -477, -192],
       [ 905,  752, -107],
       [4908, 3201,   89]])

In [3]:
np.inner(ndarray2, ndarray1)

array([[ 176,  905, 4908],
       [-477,  752, 3201],
       [-192, -107,   89]])

## III. Calculate outer product

In [4]:
np.outer(ndarray1, ndarray2)

array([[    0,     1,   100,     1,    25,    61,    -2,     8,     1],
       [    0,   -24, -2400,   -24,  -600, -1464,    48,  -192,   -24],
       [    0,     2,   200,     2,    50,   122,    -4,    16,     2],
       [    0,    78,  7800,    78,  1950,  4758,  -156,   624,    78],
       [    0,     5,   500,     5,   125,   305,   -10,    40,     5],
       [    0,     9,   900,     9,   225,   549,   -18,    72,     9],
       [    0,    12,  1200,    12,   300,   732,   -24,    96,    12],
       [    0,     8,   800,     8,   200,   488,   -16,    64,     8],
       [    0,    49,  4900,    49,  1225,  2989,   -98,   392,    49]])

In [5]:
np.outer(ndarray2, ndarray1)

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0],
       [    1,   -24,     2,    78,     5,     9,    12,     8,    49],
       [  100, -2400,   200,  7800,   500,   900,  1200,   800,  4900],
       [    1,   -24,     2,    78,     5,     9,    12,     8,    49],
       [   25,  -600,    50,  1950,   125,   225,   300,   200,  1225],
       [   61, -1464,   122,  4758,   305,   549,   732,   488,  2989],
       [   -2,    48,    -4,  -156,   -10,   -18,   -24,   -16,   -98],
       [    8,  -192,    16,   624,    40,    72,    96,    64,   392],
       [    1,   -24,     2,    78,     5,     9,    12,     8,    49]])

## IV. Calculate dot products

In [6]:
ndarray1.dot(ndarray2)

array([[  -28,  -583, -1362],
       [  -13,   275,  8114],
       [  -90,   604,  1737]])

In [7]:
ndarray2.dot(ndarray1)

array([[1278,  805, 4909],
       [2683,  589, 3216],
       [ 634,   96,  117]])

## V. Calculate the correlation matrix

In [8]:
np.corrcoef(ndarray2)

array([[ 1.        ,  0.92108658, -0.21652882],
       [ 0.92108658,  1.        ,  0.18067901],
       [-0.21652882,  0.18067901,  1.        ]])

In [9]:
np.corrcoef(ndarray1)

array([[ 1.        ,  0.51276433,  0.60210753],
       [ 0.51276433,  1.        , -0.3767235 ],
       [ 0.60210753, -0.3767235 ,  1.        ]])