# 8.1.4 Math Functions with Numpy/SciPy: Matrix Operations Part 2

######

## I. Create two 5x5 ndarrays

In [1]:
# Create ndarrays containing 10 random number
import numpy as np
import scipy.linalg as linalg # For eigenvalues

ndarray1 = np.array([[1,-24,2,0,5],[6,7,78,5,9],[3,11,12,8,49],[-1,2,4,67, 88],[0,-23,-88,100,0]]) # ndarray1.size = 25
# ndarray1.size
ndarray2 = np.array([[0,1,100,3,4],[5,1,-7,25,61],[-2,8,0,0,1],[55,66,-3,-2,99],[-100,3,4,-78,-1]]) # ndarray2.size = 25
# ndarray2.size

## II. Multiply the two matrices together:

In [2]:
np.matmul(ndarray1, ndarray2)

array([[ -624,     8,   288,  -987, -1463],
       [ -746,   994,   572,  -519,  1015],
       [-4429,   785,   395, -3554,  1438],
       [-5113,  4719,    37, -6951,  6667],
       [ 5561,  5873,  -139,  -775,  8409]])

In [3]:
np.matmul(ndarray2, ndarray1)

array([[  303,  1021,   938,  1406,  5173],
       [  -35, -1543, -5264,  7724,  1891],
       [   46,    81,   532,   140,    62],
       [  444, -3172, -3498, 10072,   546],
       [    8,  2332,  -142, -5279, -7141]])

## III. Compute the eigenvalues of the matrices:

In [4]:
linalg.eig(ndarray1)

(array([115.16962999 +0.j        ,  17.54422255+15.85688315j,
         17.54422255-15.85688315j, -31.62903754+17.44353328j,
        -31.62903754-17.44353328j]),
 array([[ 0.0355528 +0.j        , -0.69510363+0.j        ,
         -0.69510363-0.j        , -0.36860455-0.23695442j,
         -0.36860455+0.23695442j],
        [-0.28161352+0.j        ,  0.45535906+0.4498144j ,
          0.45535906-0.4498144j , -0.66836976+0.j        ,
         -0.66836976-0.j        ],
        [-0.29259956+0.j        ,  0.03008219+0.15288974j,
          0.03008219-0.15288974j,  0.36384638-0.15185806j,
          0.36384638+0.15185806j],
        [-0.80930534+0.j        ,  0.12593145+0.19929169j,
          0.12593145-0.19929169j,  0.14891003-0.25641127j,
          0.14891003+0.25641127j],
        [-0.42289501+0.j        , -0.12629924-0.10648219j,
         -0.12629924+0.10648219j, -0.12160664+0.32110899j,
         -0.12160664-0.32110899j]]))

In [5]:
linalg.eig(ndarray2)

(array([ 23.14801414+82.34711841j,  23.14801414-82.34711841j,
         -0.44860359+35.30308787j,  -0.44860359-35.30308787j,
        -47.3988211  +0.j        ]),
 array([[ 0.00167438+4.67600043e-02j,  0.00167438-4.67600043e-02j,
         -0.36889457+4.20462144e-02j, -0.36889457-4.20462144e-02j,
          0.26148662+0.00000000e+00j],
        [-0.43329574-7.89160219e-05j, -0.43329574+7.89160219e-05j,
          0.55069548-1.58381113e-01j,  0.55069548+1.58381113e-01j,
          0.70462168+0.00000000e+00j],
        [-0.01824882+3.55918433e-02j, -0.01824882-3.55918433e-02j,
         -0.03148514-1.40949951e-01j, -0.03148514+1.40949951e-01j,
         -0.1000295 +0.00000000e+00j],
        [-0.67307843+0.00000000e+00j, -0.67307843-0.00000000e+00j,
          0.63066182+0.00000000e+00j,  0.63066182-0.00000000e+00j,
         -0.53498312+0.00000000e+00j],
        [ 0.11640501-5.84705911e-01j,  0.11640501+5.84705911e-01j,
         -0.15326009+3.02849206e-01j, -0.15326009-3.02849206e-01j,
         -0.3

## IV. Calculate the correlation matrix for each of the two matrices:

In [6]:
np.corrcoef(ndarray1)

array([[ 1.        ,  0.24955475,  0.31483782,  0.45791366,  0.1071061 ],
       [ 0.24955475,  1.        , -0.09814175, -0.35501869, -0.73031863],
       [ 0.31483782, -0.09814175,  1.        ,  0.72491771, -0.06548955],
       [ 0.45791366, -0.35501869,  0.72491771,  1.        ,  0.58317526],
       [ 0.1071061 , -0.73031863, -0.06548955,  0.58317526,  1.        ]])

In [7]:
np.corrcoef(ndarray2)

array([[ 1.        , -0.46312666, -0.20626468, -0.57387297,  0.43817271],
       [-0.46312666,  1.        , -0.14294663,  0.55426807,  0.07044659],
       [-0.20626468, -0.14294663,  1.        ,  0.31485409,  0.59705538],
       [-0.57387297,  0.55426807,  0.31485409,  1.        ,  0.23761396],
       [ 0.43817271,  0.07044659,  0.59705538,  0.23761396,  1.        ]])