# 8.1.6 Math Functions with Numpy/SciPy: Random Matrix

##### OBJECTIVE: Create a matrix of random numbers that have a predefined correlation.
##### IMPORTANCE: Allows us to understand stock price movements at the portfolio level to get more complete information to value their options.

######

## STEPS:

In [1]:
# Initialize
import numpy as np
import yfinance as yf # Try PSE (PH Stocks) Package next time by Lorenzo Ampil

#### a. Pick 10 stocks from any stock exchange and get their last 10 closing prices – put these into an ndarray, and calculate the covariance matrix:

In [2]:
# A. PICK STOCKS:

## EXCHANGE: US (NYSE/NASDAQ)
## Theme: Top 10 BRK.A Holdings (per Investors.com):
## STOCKS: BAC, AAPL, KO, KHC, VZ, AXP, USB, BK, GM, KR (As of 8.2.2021).

## Import:
# (1) Bank of America
bac = yf.Ticker("BAC")
bacData = bac.history(period="max")

# (2) Apple
aapl = yf.Ticker("AAPL")
aaplData = aapl.history(period="max")

# (3) Coca-Cola
ko = yf.Ticker("KO")
koData = ko.history(period="max")

# (4) Kraft Heinz
khc = yf.Ticker("KHC")
khcData = khc.history(period="max")

# (5) Verizon
vz = yf.Ticker("VZ")
vzData = vz.history(period="max")

# (6) American Express
axp = yf.Ticker("AXP")
axpData = axp.history(period="max")

# (7) U.S. Bancorp
usb = yf.Ticker("USB")
usbData = usb.history(period="max")

# (8) Bank of New York Mellon
bk = yf.Ticker("bk")
bkData = bk.history(period="max")

# (9) General Motors 
gm = yf.Ticker("GM")
gmData = gm.history(period="max")

# (10) Kroger
kr = yf.Ticker("KR")
krData = kr.history(period="max")

## Get Last 10 CLOSING Prices. Put these into an ndarray:
priceSubset = np.array([bacData.Close[-10:], aaplData.Close[-10:], koData.Close[-10:], khcData.Close[-10:], vzData.Close[-10:], axpData.Close[-10:], 
                           usbData.Close[-10:], bkData.Close[-10:], gmData.Close[-10:], krData.Close[-10:]])

## Calculate Covariance Matrix:
covarMatrix = np.cov(priceSubset, bias = True)
# covarMatrix.size. CORRECT: 10 x 10 matrix.

covarMatrix

array([[ 0.10369071, -0.11729753, -0.02760867, -0.09006254, -0.02486616,
        -0.2014214 ,  0.02567328,  0.23289175,  0.06741039,  0.21659199],
       [-0.11729753,  1.53376087,  0.06513015,  0.27859596,  0.01295967,
         0.97677188,  0.07345041, -0.36662075, -0.35590372, -0.17889282],
       [-0.02760867,  0.06513015,  0.0934089 ,  0.1301244 ,  0.03669242,
         0.23582361,  0.03998703, -0.05402357,  0.20815211, -0.09195362],
       [-0.09006254,  0.27859596,  0.1301244 ,  0.29870433,  0.06690856,
         0.49299393,  0.11005192, -0.29075769,  0.2737521 , -0.30164827],
       [-0.02486616,  0.01295967,  0.03669242,  0.06690856,  0.03316119,
         0.17478769,  0.03109696, -0.08987583,  0.04887261, -0.09724739],
       [-0.2014214 ,  0.97677188,  0.23582361,  0.49299393,  0.17478769,
         2.14706124,  0.28578202, -0.84642686, -0.52873045, -0.96672753],
       [ 0.02567328,  0.07345041,  0.03998703,  0.11005192,  0.03109696,
         0.28578202,  0.12960075, -0.07545218

#### b. Use numpy.random’s multivariate_normal to create a correlated array of random numbers, based on the above covariance matrix.

In [3]:
# Get Mean:
# https://quantnet.com/threads/8-1-6-b-mean-to-use-for-multivariate_normal.46435/ ... Any approach (either means of stock prices / 0's) is fine. I choose to use zeroes.
mean = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])  # Calculate means closing price of each stocks, pass to a list then convert to an array. One mean per stock.
# means.size. Correct

# Get Matrix:
covarMatrix # from above

# Randomize possible variances. Number of elements for each stock = number of stock prices:
lenCov =  10

# Calculate:
corrArray = np.random.multivariate_normal(mean, covarMatrix, lenCov)
corrArray

array([[-0.58879352,  0.67562357,  0.48179989,  0.56280884,  0.12507948,
         2.61324825, -0.10555045, -1.25749913, -0.79109314, -1.6613444 ],
       [-0.55455535, -2.22026328, -0.07240931, -0.10184296,  0.10870305,
        -1.27527661, -0.49310337, -0.80697836,  0.08827253, -0.4071846 ],
       [-0.10402337, -1.26585956,  0.17133664,  0.47282038, -0.07717016,
        -2.65763469, -0.34782585,  0.18896497,  4.18639264, -0.00662879],
       [ 0.74334947,  0.96517581, -0.56041955, -1.01203794, -0.21550797,
        -1.28637902, -0.0638381 ,  1.71069116, -0.04633287,  2.51278361],
       [ 0.54664636, -1.16540901, -0.19652563, -0.52968294, -0.09245557,
        -3.09124442, -0.15608577,  1.90362157,  2.10839499,  2.6214466 ],
       [ 0.06792898, -2.0711732 , -0.23967226, -0.30248572, -0.14360206,
        -1.53357973, -0.01673264,  0.11475231,  0.09655792,  0.23717571],
       [ 0.12264898,  1.68534576, -0.11271415, -0.20946694, -0.133659  ,
        -0.38932476, -0.09543257,  0.7646781 

#### c. Use np.random’s standard_normal function to create an array of uncorrelated random numbers. Use the following formula to create a correlated array of random numbers:

In [4]:
# Derive uncorr for a matrix of size (10 x 10):
uncorr = np.random.standard_normal(100) # Still just a list of len = 100.
uncorr = np.resize(uncorr, (10, 10)) # Create 10 x 10 matrix from the list above
# uncorr

# Cholesky decomposition
L = np.linalg.cholesky(covarMatrix) # per formula

# Correlated array of random numbers
corr = np.dot(L, uncorr) # per formula

corr # LinAlgError: Matrix is not positive definite depending on rng

array([[-2.03816689e-01, -7.47670591e-03,  3.60656744e-01,
         4.59655003e-01,  4.31808809e-01, -3.54717570e-01,
         2.24432727e-04, -3.21020275e-01,  1.51676365e-01,
        -6.22073816e-01],
       [-3.44717581e-02,  2.27216225e-01,  2.05514903e+00,
        -1.03956973e+00,  1.67038085e-01,  7.23009595e-02,
         2.40088938e+00,  4.00705872e-01, -1.68722400e+00,
        -1.49085460e+00],
       [ 1.32971556e-03, -1.34403788e-01,  9.03407760e-02,
         2.11489138e-02,  4.22968232e-02,  1.39214501e-01,
        -1.66812110e-01, -1.36141859e-01, -9.32924906e-02,
        -1.37476253e-01],
       [ 4.28707328e-01, -6.47174006e-03,  5.95791658e-03,
        -2.35423961e-01,  5.32957487e-01,  1.21582517e-01,
        -3.14081654e-02,  7.06128288e-02, -5.51333443e-01,
         3.62609634e-01],
       [ 1.49869026e-01,  1.91369359e-01,  7.51118770e-03,
        -2.19185976e-01,  9.69533697e-02, -6.65334263e-02,
        -1.65315661e-01, -6.27510778e-02, -3.76520236e-01,
         1.